### ISSUE TITLE
Suggestion for importing jsx file

### ISSUE THREAD

**Issue by jerrychen1013** [pawaniitd/laravel-elixir-react-hmr#1]
Hi, thanks for this great package, it makes me more convenience without reload manually.

But I met one issue that is when I import jsx file without the extension, webpack will not find it.
//It will not work
ex. import Aside from './Aside';   

//It works
ex. import Aside from './Aside.jsx'

I solved it when revised webpack.config.js with code below:
`resolve: {
            extensions: ['', '.js', '.json', '.jsx' ]
}`

So maybe this package could add it and support jsx extension when imports file.

**Comment by psamd** [comment]
Thanks for pointing it out and providing the solution too. Will add it to the webpack config
